<?xml version="1.0"?>

<definitions name="AppointmentService"
    targetNamespace="http://example.com/appointment"
    xmlns:tns="http://example.com/appointment"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">

    <portType name="PatientPort">

    </portType>

    <service name="PatientService">
        <documentation>Patient SOAP API</documentation>
        <port name="PatientPort" binding="tns:PatientBinding">
            <soap:address location="http://localhost:8000/soap/patient" />
        </port>
    </service>
</definitions>